[Scripts] Remove need of PyQt5 if gui is not used
SofaDefrost/ModelOrderReduction pull request #123
Opened 2024-05-07 13:37 UTC by epernod

Method `update_progress` was present twice in the code: One in the `mor/gui/utility.py` and on in `mor/utility/utility.py`.

Only keep the one in gui/utility.py as it is bringing visual feedback for the UI. 

This allows to use the [tools/modelOrderReduction.py](https://github.com/SofaDefrost/ModelOrderReduction/compare/master...InfinyTech3D:ModelOrderReduction:nogui#diff-065fdee9ecd549d0cf73a359a1e3944b5b270ec1dd0fdf47a5a38e4d4a52cf4b) without gui to faster run benchmarks.

2024-05-07 13:50 UTC, alxbilger approved these changes

2024-05-21 07:58 UTC, VannesteFelix commented on tools/modelOrderReduction.py
> +    originalScene = "/home/felix_v/SOFA/plugins/ModelOrderReduction/tools/test/sofa_test_scene/diamondRobot.py"
Can you please remove my hard-coded path and change it to a generic indication ?
Sorry about that I shouldn't have committed it in the first place.
Like so for example :
```
originalScene = None # replace with path to your scene
outputDir = None # replace with path to folder where results will be
```

2024-05-21 10:17 UTC, VannesteFelix requested changes
Sorry last little things...

2024-05-21 12:25 UTC, epernod commented on tools/modelOrderReduction.py
> +if useGui:
I find it more clean to not put import in middle of the code.

2024-05-21 14:08 UTC, merged